spring.application.name=clientdome
server.port = 8011

spring.security.user.name=admin
spring.security.user.password=admin123

descope.project-id=P31VrLEaibrMFYwGQpzKrLNUChHQ


spring.security.oauth2.client.registration.descope-m2m.provider=descope-provider
spring.security.oauth2.client.registration.descope-m2m.client-id=UDMxVnJMRWFpYnJNRll3R1FwektyTE5VQ2hIUTpUUEEzMWoySmczRFRKOWFRUW5JclpKY2tMbUJoclA=
spring.security.oauth2.client.registration.descope-m2m.client-secret=7zBobbHl8Ha9ezBuE46jZxrB05JK4dUwfCTyrqwZ0X5
spring.security.oauth2.client.registration.descope-m2m.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.descope-m2m.scope=doc:extract:aadhaar

spring.security.oauth2.client.provider.descope-provider.token-uri=https://api.descope.com/oauth2/v1/apps/token
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://api.descope.com/v1/apps/P31VrLEaibrMFYwGQpzKrLNUChHQ

# ===============================================
# Specialist Dome Service URLs
# ===============================================
service.url.aadhardome=http://localhost:8081/extract
service.url.pandome=http://localhost:8082/extract
service.url.sheetdome=http://localhost:8083/extract
service.url.facedome=http://localhost:8084/analyze
service.url.validatordome=http://localhost:8085/validate

gemini.api.key=${GOOGLE_API_KEY}
gemini.model.name=gemini-2.5-flash

server.servlet.session.persistent=false